cluster_provider_strategy = "kubeconfig"
port = "8085"
stateless = true
log_level = 2
toolsets = ["core", "kyma", "overview"]
kubeconfig = "/Users/I546341/kubeconfigs/kubeconfig-token--kymatunas--comp-tests-0.yaml"